

name: ccTopology


on:
  push:
    paths:
      - 'ccTopology/**'
      - 'go.sum'
      - 'go.mod'

jobs:
  golang_unit_tests:
    name: Golang unit tests for ccTopology
    runs-on: ubuntu-latest
    steps:
    # See: https://github.com/marketplace/actions/checkout
    # Checkout git repository and submodules
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # See: https://github.com/marketplace/actions/setup-go-environment
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true

    - name: Setup Hwloc
      run: |
        sudo apt --assume-yes install hwloc
        ln -s $(find /usr/lib -name "libhwloc*" | head -n 1) libhwloc.so


    # Run 'go test' in specified test target
    - name: Run Golang tests
      run: |
        cd ccTopology
        go test
