

name: util


on:
  push:
    paths:
      - 'util/**'
      - 'go.sum'
      - 'go.mod'

jobs:
  golang_unit_tests:
    name: Golang unit tests for util
    runs-on: ubuntu-latest
    steps:
    # See: https://github.com/marketplace/actions/checkout
    # Checkout git repository and submodules
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # See: https://github.com/marketplace/actions/setup-go-environment
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true

    # Run 'go test' in specified test target
    - name: Run Golang tests
      run: |
        cd util
        go test
